# Generated by Django 4.2.6 on 2023-11-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_document_managers_comment_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='documentpermission',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
