# Generated by Django 4.2.6 on 2023-10-26 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(default='EG4MylMrqfI50VZuFjNlLLOJoJHyPgbPFonfxAfB5t78OJvjcp3kSOFoF6mfKKgP52gT29HrSphbGxYUHojXgWwVrmREIRIy5W2E', max_length=100, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
