# Generated by Django 4.2.6 on 2023-10-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_role_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'USER'), ('Provider', 'PROVIDER'), ('Admin', 'ADMIN'), ('Employee', 'EMPLOYEE'), ('Manager', 'MANAGER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='mE27A7JlelVkkJhwXmd0ERlUNS5xOHSZam3vRj7oFPnWxLyGNTWXvDh2Bl1Ontm31INHp6VDlnMU5rsySdfJNeWzRRrIE3iDEgm3', max_length=100, unique=True),
        ),
    ]
