# Generated by Django 4.2.6 on 2023-10-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_role_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='kfgsZK7HMvlkwrxGaM4LN5Q3TfSqheX4CEGRWnY9C14xdZTtN2bvxbuDXPNJ3yesxXuzj7daQo3HaJhOYzSysrq6FS6w84tmYZt3', max_length=100, unique=True),
        ),
    ]
