# Generated by Django 4.2.6 on 2023-10-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='YPccb9D5IzGUpZkiDiMT7dtqqFNTbzkDUgiyl6Kh4Ae9uR52TgPnTySPjnc7Bl7BwFTox8XGH9B06WSLYzH0axdQJEbIY1w5mCTv', max_length=100, unique=True),
        ),
    ]
