# Generated by Django 4.2.6 on 2023-11-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='2tfW4Z5neOQ0gcPYFlX5kLvs3eohLQDZXRHrB9SA6nmeHndZKmuQtDRCusLhowYAvZvYVYd3bxb668VrtJZPjspvajHdtKs4OmVO', max_length=100, unique=True),
        ),
    ]
