# Generated by Django 4.2.6 on 2023-11-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='9jMAbIVN8NMUmq7EQWKnVYtpZrjHxr2LBxmXK2gCvob0PVbQgV1lE6yIMggUJoBRUV6npdvQFGkcTxf7Q0jqlLy1IxrN6HYmMP6o', max_length=100, unique=True),
        ),
    ]
