# Generated by Django 4.2.6 on 2023-11-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customuser_is_deleted_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='gloalVqdcQ8TIPCZsg4KgoiY5W5QiMNIcfEiVSWQvhQVQJo1MTAJaHVFqxBZmD5LVUUYt8UevERdUnHSUjpM3LYOWN4jw9Zurbms', max_length=100, unique=True),
        ),
    ]
