# Generated by Django 4.2.6 on 2023-11-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='BdfjQxxDhNuV3tC8198Mfnl2FVcDkwAr2WjS9rznMWS2kJQYrpXqgBTvZH0bNANL81Zft69hszKzni4qvQQnGGNf9ll5WjRPpt3H', max_length=100, unique=True),
        ),
    ]
