# Generated by Django 4.2.6 on 2023-11-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='MmyuMM7Y7iut0vVikdumppUyYegh4vyXveAyxRgk44WGMaMfE7RiRSZfgGuTqSl5oVgTQhsO9jJMbZ1pGEfcZXNCpli1MTGGRbTQ', max_length=100, unique=True),
        ),
    ]
