# Generated by Django 4.2.6 on 2023-11-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='iIsvVJ3Q4RKYrCMLeaE7kQOZ5sgOkv2GnoBtZa7N62n5mAZPveIVBlJQmnxO4shtL3uAm1Ti5i62giXQhKVrloZUhPlsV28xBGJ1', max_length=100, unique=True),
        ),
    ]
