# Generated by Django 4.2.6 on 2023-11-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='2Dpr1pnaMaZGDCvFETWq0OQ4a3PtN7s1GkLfU3V5r72iW0OEWEJbvWKepCrnzcbF8hw2Ch6S4fnTT8d9vYRMyJIb0wcIWpuQzuwv', max_length=100, unique=True),
        ),
    ]
