# Generated by Django 4.2.6 on 2023-11-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='EA7ENvzoJbHQbddgr2F2xP4bUo75nuYI5nH8CRuW10JWwLSfwtzxU06xBXK2AGGm7zDBtyOxB7j3XMSi0P7uvuobZZTnAUs6TR4y', max_length=100, unique=True),
        ),
    ]
