# Generated by Django 4.2.6 on 2023-11-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='8ZLXAqRQlMRmggSYZtuzu3k4NZznaUqxQ2JafuKhDmnqJ7dThOdcMz6qhGEF6VnwAQhfwLxzqZ0Ha8zqRvxjbAqqjbBgdziKelDY', max_length=100, unique=True),
        ),
    ]
