# Generated by Django 4.2.6 on 2023-11-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='JtCoZWHv4oOvckDMeF9sGQHptFHaP3IKLczu3ETkV3fXzxOK3r3GcAhgVPCyLyouxW9TAUEABQYUjrYohRH7N7m3NzojXsrlS53s', max_length=100, unique=True),
        ),
    ]
